export const BACKGROUND_COLOR = "#ffffff"
export const BORDER_COLOR = "#e1e1e1"
export const DEFAULT_TEXT_COLOR = "#4b4b4b"
export const DISABLED_TEXT_COLOR = "#b3b3b3"
export const PRIMARY_TEAL_COLOR = "#20b2aa"
export const SECONDARY_TEAL_COLOR = "#188781"