/* eslint-disable */
import { Surah } from "../../../types/surah"

export const SURAHS: Surah[] = [
  {
    "name": "الفاتحة",
    "number": 1,
    "numberOfAyahs": 7,
    "hasBismillah": false,
    "queryIndexes": [
      "1",
      "the opener",
      "opener",
      "the",
      "الفاتحة",
      "al fatihah",
      "al-fatihah",
      "fatihah",
      "al",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 5,
    },
    "slug": "al-fatihah",
    "translations": [
      {
        "language": "en",
        "text": "The Opener",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Al-Fatihah",
      },
    ],
    "id": "1",
    "unicode": "&#33;",
  },
  {
    "name": "البقرة",
    "number": 2,
    "numberOfAyahs": 286,
    "hasBismillah": true,
    "queryIndexes": [
      "2",
      "the cow",
      "cow",
      "the",
      "البقرة",
      "al baqarah",
      "al-baqarah",
      "baqarah",
      "al",
      "madinah",
      "medinan",
      "medinah",
    ],
    "revelation": {
      "place": "medinan",
      "order": 87,
    },
    "slug": "al-baqarah",
    "translations": [
      {
        "language": "en",
        "text": "The Cow",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Al-Baqarah",
      },
    ],
    "id": "2",
    "unicode": "&#34;",
  },
  {
    "name": "آل عمران",
    "number": 3,
    "numberOfAyahs": 200,
    "hasBismillah": true,
    "queryIndexes": [
      "3",
      "family of imran",
      "of imran",
      "imran",
      "family",
      "of",
      "آل عمران",
      "عمران",
      "آل",
      "ali 'imran",
      "ali-imran",
      "'imran",
      "ali",
      "madinah",
      "medinan",
      "medinah",
    ],
    "revelation": {
      "place": "medinan",
      "order": 89,
    },
    "slug": "ali-imran",
    "translations": [
      {
        "language": "en",
        "text": "Family of Imran",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Ali 'Imran",
      },
    ],
    "id": "3",
    "unicode": "&#35;",
  },
  {
    "name": "النساء",
    "number": 4,
    "numberOfAyahs": 176,
    "hasBismillah": true,
    "queryIndexes": [
      "4",
      "the women",
      "women",
      "the",
      "النساء",
      "an nisa",
      "an-nisa",
      "nisa",
      "an",
      "madinah",
      "medinan",
      "medinah",
    ],
    "revelation": {
      "place": "medinan",
      "order": 92,
    },
    "slug": "an-nisa",
    "translations": [
      {
        "language": "en",
        "text": "The Women",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "An-Nisa",
      },
    ],
    "id": "4",
    "unicode": "&#36;",
  },
  {
    "name": "المائدة",
    "number": 5,
    "numberOfAyahs": 120,
    "hasBismillah": true,
    "queryIndexes": [
      "5",
      "the table spread",
      "table spread",
      "spread",
      "the",
      "table",
      "المائدة",
      "al ma'idah",
      "al-maidah",
      "ma'idah",
      "al",
      "madinah",
      "medinan",
      "medinah",
    ],
    "revelation": {
      "place": "medinan",
      "order": 112,
    },
    "slug": "al-maidah",
    "translations": [
      {
        "language": "en",
        "text": "The Table Spread",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Al-Ma'idah",
      },
    ],
    "id": "5",
    "unicode": "&#37;",
  },
  {
    "name": "الأنعام",
    "number": 6,
    "numberOfAyahs": 165,
    "hasBismillah": true,
    "queryIndexes": [
      "6",
      "the cattle",
      "cattle",
      "the",
      "الأنعام",
      "al an'am",
      "al-anam",
      "an'am",
      "al",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 55,
    },
    "slug": "al-anam",
    "translations": [
      {
        "language": "en",
        "text": "The Cattle",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Al-An'am",
      },
    ],
    "id": "6",
    "unicode": "&#38;",
  },
  {
    "name": "الأعراف",
    "number": 7,
    "numberOfAyahs": 206,
    "hasBismillah": true,
    "queryIndexes": [
      "7",
      "the heights",
      "heights",
      "the",
      "الأعراف",
      "al a'raf",
      "al-araf",
      "a'raf",
      "al",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 39,
    },
    "slug": "al-araf",
    "translations": [
      {
        "language": "en",
        "text": "The Heights",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Al-A'raf",
      },
    ],
    "id": "7",
    "unicode": "&#39;",
  },
  {
    "name": "الأنفال",
    "number": 8,
    "numberOfAyahs": 75,
    "hasBismillah": true,
    "queryIndexes": [
      "8",
      "the spoils of war",
      "spoils of war",
      "of war",
      "war",
      "the",
      "spoils",
      "of",
      "الأنفال",
      "al anfal",
      "al-anfal",
      "anfal",
      "al",
      "madinah",
      "medinan",
      "medinah",
    ],
    "slug": "al-anfal",
    "revelation": {
      "place": "medinan",
      "order": 88,
    },
    "translations": [
      {
        "language": "en",
        "text": "The Spoils of War",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Al-Anfal",
      },
    ],
    "id": "8",
    "unicode": "&#40;",
  },
  {
    "name": "التوبة",
    "number": 9,
    "numberOfAyahs": 129,
    "hasBismillah": false,
    "queryIndexes": [
      "9",
      "the repentance",
      "repentance",
      "the",
      "التوبة",
      "at tawbah",
      "at-tawbah",
      "tawbah",
      "at",
      "madinah",
      "medinan",
      "medinah",
    ],
    "slug": "at-tawbah",
    "revelation": {
      "place": "medinan",
      "order": 113,
    },
    "translations": [
      {
        "language": "en",
        "text": "The Repentance",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "At-Tawbah",
      },
    ],
    "id": "9",
    "unicode": "&#41;",
  },
  {
    "name": "يونس",
    "number": 10,
    "numberOfAyahs": 109,
    "hasBismillah": true,
    "queryIndexes": [
      "10",
      "jonah",
      "يونس",
      "yunus",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 51,
    },
    "translations": [
      {
        "language": "en",
        "text": "Jonah",
      },
    ],
    "slug": "yunus",
    "transliterations": [
      {
        "language": "en",
        "text": "Yunus",
      },
    ],
    "id": "10",
    "unicode": "&#42;",
  },
  {
    "name": "هود",
    "number": 11,
    "numberOfAyahs": 123,
    "hasBismillah": true,
    "queryIndexes": [
      "11",
      "hud",
      "هود",
      "hud",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 52,
    },
    "slug": "hud",
    "translations": [
      {
        "language": "en",
        "text": "Hud",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Hud",
      },
    ],
    "id": "11",
    "unicode": "&#43;",
  },
  {
    "name": "يوسف",
    "number": 12,
    "numberOfAyahs": 111,
    "hasBismillah": true,
    "queryIndexes": [
      "12",
      "joseph",
      "يوسف",
      "yusuf",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 53,
    },
    "slug": "yusuf",
    "translations": [
      {
        "language": "en",
        "text": "Joseph",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Yusuf",
      },
    ],
    "id": "12",
    "unicode": "&#44;",
  },
  {
    "name": "الرعد",
    "number": 13,
    "numberOfAyahs": 43,
    "hasBismillah": true,
    "queryIndexes": [
      "13",
      "the thunder",
      "thunder",
      "the",
      "الرعد",
      "ar ra'd",
      "ar-rad",
      "ra'd",
      "ar",
      "madinah",
      "medinan",
      "medinah",
    ],
    "revelation": {
      "place": "medinan",
      "order": 96,
    },
    "slug": "ar-rad",
    "translations": [
      {
        "language": "en",
        "text": "The Thunder",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Ar-Ra'd",
      },
    ],
    "id": "13",
    "unicode": "&#45;",
  },
  {
    "name": "ابراهيم",
    "number": 14,
    "numberOfAyahs": 52,
    "hasBismillah": true,
    "queryIndexes": [
      "14",
      "abrahim",
      "ابراهيم",
      "ibrahim",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 72,
    },
    "slug": "ibrahim",
    "translations": [
      {
        "language": "en",
        "text": "Abrahim",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Ibrahim",
      },
    ],
    "id": "14",
    "unicode": "&#46;",
  },
  {
    "name": "الحجر",
    "number": 15,
    "numberOfAyahs": 99,
    "hasBismillah": true,
    "queryIndexes": [
      "15",
      "the rocky tract",
      "rocky tract",
      "tract",
      "the",
      "rocky",
      "الحجر",
      "al hijr",
      "al-hijr",
      "hijr",
      "al",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 54,
    },
    "slug": "al-hijr",
    "translations": [
      {
        "language": "en",
        "text": "The Rocky Tract",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Al-Hijr",
      },
    ],
    "id": "15",
    "unicode": "&#47;",
  },
  {
    "name": "النحل",
    "number": 16,
    "numberOfAyahs": 128,
    "hasBismillah": true,
    "queryIndexes": [
      "16",
      "the bee",
      "bee",
      "the",
      "النحل",
      "an nahl",
      "an-nahl",
      "nahl",
      "an",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 70,
    },
    "slug": "an-nahl",
    "translations": [
      {
        "language": "en",
        "text": "The Bee",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "An-Nahl",
      },
    ],
    "id": "16",
    "unicode": "&#48;",
  },
  {
    "name": "الإسراء",
    "number": 17,
    "numberOfAyahs": 111,
    "hasBismillah": true,
    "queryIndexes": [
      "17",
      "the night journey",
      "night journey",
      "journey",
      "the",
      "night",
      "الإسراء",
      "al isra",
      "al-isra",
      "isra",
      "al",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 50,
    },
    "slug": "al-isra",
    "translations": [
      {
        "language": "en",
        "text": "The Night Journey",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Al-Isra",
      },
    ],
    "id": "17",
    "unicode": "&#49;",
  },
  {
    "name": "الكهف",
    "number": 18,
    "numberOfAyahs": 110,
    "hasBismillah": true,
    "queryIndexes": [
      "18",
      "the cave",
      "cave",
      "the",
      "الكهف",
      "al kahf",
      "kahf",
      "al",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 69,
    },
    "slug": "al-kahf",
    "translations": [
      {
        "language": "en",
        "text": "The Cave",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Al-Kahf",
      },
    ],
    "id": "18",
    "unicode": "&#50;",
  },
  {
    "name": "مريم",
    "number": 19,
    "numberOfAyahs": 98,
    "hasBismillah": true,
    "queryIndexes": [
      "19",
      "mary",
      "مريم",
      "maryam",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 44,
    },
    "slug": "maryam",
    "translations": [
      {
        "language": "en",
        "text": "Mary",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Maryam",
      },
    ],
    "id": "19",
    "unicode": "&#51;",
  },
  {
    "name": "طه",
    "number": 20,
    "numberOfAyahs": 135,
    "hasBismillah": true,
    "queryIndexes": [
      "20",
      "ta ha",
      "ha",
      "ta",
      "طه",
      "taha",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 45,
    },
    "slug": "ta-ha",
    "translations": [
      {
        "language": "en",
        "text": "Ta-Ha",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Taha",
      },
    ],
    "id": "20",
    "unicode": "&#52;",
  },
  {
    "name": "الأنبياء",
    "number": 21,
    "numberOfAyahs": 112,
    "hasBismillah": true,
    "queryIndexes": [
      "21",
      "the prophets",
      "prophets",
      "the",
      "الأنبياء",
      "al anbya",
      "anbya",
      "al",
      "makkah",
      "meccan",
    ],
    "slug": "al-anbya",
    "revelation": {
      "place": "meccan",
      "order": 73,
    },
    "translations": [
      {
        "language": "en",
        "text": "The Prophets",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Al-Anbya",
      },
    ],
    "id": "21",
    "unicode": "&#53;",
  },
  {
    "name": "الحج",
    "number": 22,
    "numberOfAyahs": 78,
    "hasBismillah": true,
    "queryIndexes": [
      "22",
      "the pilgrimage",
      "pilgrimage",
      "the",
      "الحج",
      "al haj",
      "haj",
      "al",
      "madinah",
      "medinan",
      "medinah",
    ],
    "revelation": {
      "place": "medinan",
      "order": 103,
    },
    "slug": "al-haj",
    "translations": [
      {
        "language": "en",
        "text": "The Pilgrimage",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Al-Haj",
      },
    ],
    "id": "22",
    "unicode": "&#54;",
  },
  {
    "name": "المؤمنون",
    "number": 23,
    "numberOfAyahs": 118,
    "hasBismillah": true,
    "queryIndexes": [
      "23",
      "the believers",
      "believers",
      "the",
      "المؤمنون",
      "al mu'minun",
      "mu'minun",
      "al",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 74,
    },
    "slug": "al-muminun",
    "translations": [
      {
        "language": "en",
        "text": "The Believers",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Al-Mu'minun",
      },
    ],
    "id": "23",
    "unicode": "&#55;",
  },
  {
    "name": "النور",
    "number": 24,
    "numberOfAyahs": 64,
    "hasBismillah": true,
    "queryIndexes": [
      "24",
      "the light",
      "light",
      "the",
      "النور",
      "an nur",
      "nur",
      "an",
      "madinah",
      "medinan",
      "medinah",
    ],
    "revelation": {
      "place": "medinan",
      "order": 102,
    },
    "slug": "an-nur",
    "translations": [
      {
        "language": "en",
        "text": "The Light",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "An-Nur",
      },
    ],
    "id": "24",
    "unicode": "&#56;",
  },
  {
    "name": "الفرقان",
    "number": 25,
    "numberOfAyahs": 77,
    "hasBismillah": true,
    "queryIndexes": [
      "25",
      "the criterian",
      "criterian",
      "the",
      "الفرقان",
      "al furqan",
      "furqan",
      "al",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 42,
    },
    "slug": "al-furqan",
    "translations": [
      {
        "language": "en",
        "text": "The Criterian",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Al-Furqan",
      },
    ],
    "id": "25",
    "unicode": "&#57;",
  },
  {
    "name": "الشعراء",
    "number": 26,
    "numberOfAyahs": 227,
    "hasBismillah": true,
    "queryIndexes": [
      "26",
      "the poets",
      "poets",
      "the",
      "الشعراء",
      "ash shu'ara",
      "shu'ara",
      "ash",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 47,
    },
    "slug": "ash-shuara",
    "translations": [
      {
        "language": "en",
        "text": "The Poets",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Ash-Shu'ara",
      },
    ],
    "id": "26",
    "unicode": "&#58;",
  },
  {
    "name": "النمل",
    "number": 27,
    "numberOfAyahs": 93,
    "hasBismillah": true,
    "queryIndexes": [
      "27",
      "the ant",
      "ant",
      "the",
      "النمل",
      "an naml",
      "naml",
      "an",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 48,
    },
    "slug": "an-naml",
    "translations": [
      {
        "language": "en",
        "text": "The Ant",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "An-Naml",
      },
    ],
    "id": "27",
    "unicode": "&#59;",
  },
  {
    "name": "القصص",
    "number": 28,
    "numberOfAyahs": 88,
    "hasBismillah": true,
    "queryIndexes": [
      "28",
      "the stories",
      "stories",
      "the",
      "القصص",
      "al qasas",
      "qasas",
      "al",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 49,
    },
    "slug": "al-qasas",
    "translations": [
      {
        "language": "en",
        "text": "The Stories",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Al-Qasas",
      },
    ],
    "id": "28",
    "unicode": "&#60;",
  },
  {
    "name": "العنكبوت",
    "number": 29,
    "numberOfAyahs": 69,
    "hasBismillah": true,
    "queryIndexes": [
      "29",
      "the spider",
      "spider",
      "the",
      "العنكبوت",
      "al 'ankabut",
      "'ankabut",
      "al",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 85,
    },
    "slug": "al-ankabut",
    "translations": [
      {
        "language": "en",
        "text": "The Spider",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Al-'Ankabut",
      },
    ],
    "id": "29",
    "unicode": "&#61;",
  },
  {
    "name": "الروم",
    "number": 30,
    "numberOfAyahs": 60,
    "hasBismillah": true,
    "queryIndexes": [
      "30",
      "the romans",
      "romans",
      "the",
      "الروم",
      "ar rum",
      "rum",
      "ar",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 84,
    },
    "slug": "ar-rum",
    "translations": [
      {
        "language": "en",
        "text": "The Romans",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Ar-Rum",
      },
    ],
    "id": "30",
    "unicode": "&#62;",
  },
  {
    "name": "لقمان",
    "number": 31,
    "numberOfAyahs": 34,
    "hasBismillah": true,
    "queryIndexes": [
      "31",
      "luqman",
      "لقمان",
      "luqman",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 57,
    },
    "slug": "luqman",
    "translations": [
      {
        "language": "en",
        "text": "Luqman",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Luqman",
      },
    ],
    "id": "31",
    "unicode": "&#63;",
  },
  {
    "name": "السجدة",
    "number": 32,
    "numberOfAyahs": 30,
    "hasBismillah": true,
    "queryIndexes": [
      "32",
      "the prostration",
      "prostration",
      "the",
      "السجدة",
      "as sajdah",
      "sajdah",
      "as",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 75,
    },
    "slug": "as-sajdah",
    "translations": [
      {
        "language": "en",
        "text": "The Prostration",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "As-Sajdah",
      },
    ],
    "id": "32",
    "unicode": "&#64;",
  },
  {
    "name": "الأحزاب",
    "number": 33,
    "numberOfAyahs": 73,
    "hasBismillah": true,
    "queryIndexes": [
      "33",
      "the combined forces",
      "combined forces",
      "forces",
      "the",
      "combined",
      "الأحزاب",
      "al ahzab",
      "ahzab",
      "al",
      "madinah",
      "medinan",
      "medinah",
    ],
    "revelation": {
      "place": "medinan",
      "order": 90,
    },
    "slug": "al-ahzab",
    "translations": [
      {
        "language": "en",
        "text": "The Combined Forces",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Al-Ahzab",
      },
    ],
    "id": "33",
    "unicode": "&#97;",
  },
  {
    "name": "سبإ",
    "number": 34,
    "numberOfAyahs": 54,
    "hasBismillah": true,
    "queryIndexes": [
      "34",
      "sheba",
      "سبإ",
      "saba",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 58,
    },
    "slug": "sheba",
    "translations": [
      {
        "language": "en",
        "text": "Sheba",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Saba",
      },
    ],
    "id": "34",
    "unicode": "&#65;",
  },
  {
    "name": "فاطر",
    "number": 35,
    "numberOfAyahs": 45,
    "hasBismillah": true,
    "queryIndexes": [
      "35",
      "originator",
      "فاطر",
      "fatir",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 43,
    },
    "slug": "fatir",
    "translations": [
      {
        "language": "en",
        "text": "Originator",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Fatir",
      },
    ],
    "id": "35",
    "unicode": "&#98;",
  },
  {
    "name": "يس",
    "number": 36,
    "numberOfAyahs": 83,
    "hasBismillah": true,
    "queryIndexes": [
      "36",
      "ya sin",
      "yasin",
      "yaseen",
      "sin",
      "ya",
      "يس",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 41,
    },
    "slug": "yaseen",
    "translations": [
      {
        "language": "en",
        "text": "Ya Sin",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Ya-Sin",
      },
    ],
    "id": "36",
    "unicode": "&#66;",
  },
  {
    "name": "الصافات",
    "number": 37,
    "numberOfAyahs": 182,
    "hasBismillah": true,
    "queryIndexes": [
      "37",
      "those who set the ranks",
      "who set the ranks",
      "set the ranks",
      "the ranks",
      "ranks",
      "those",
      "who",
      "set",
      "the",
      "الصافات",
      "as saffat",
      "saffat",
      "as",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 56,
    },
    "slug": "as-safat",
    "translations": [
      {
        "language": "en",
        "text": "Those who set the Ranks",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "As-Saffat",
      },
    ],
    "id": "37",
    "unicode": "&#99;",
  },
  {
    "name": "ص",
    "number": 38,
    "numberOfAyahs": 88,
    "hasBismillah": true,
    "queryIndexes": [
      "38",
      "the letter \"saad\"",
      "letter \"saad\"",
      "\"saad\"",
      "the",
      "letter",
      "ص",
      "sad",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 38,
    },
    "slug": "saad",
    "translations": [
      {
        "language": "en",
        "text": "The Letter \"Saad\"",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Sad",
      },
    ],
    "id": "38",
    "unicode": "&#67;",
  },
  {
    "name": "الزمر",
    "number": 39,
    "numberOfAyahs": 75,
    "hasBismillah": true,
    "queryIndexes": [
      "39",
      "the troops",
      "troops",
      "the",
      "الزمر",
      "az zumar",
      "zumar",
      "az",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 59,
    },
    "slug": "az-zumar",
    "translations": [
      {
        "language": "en",
        "text": "The Troops",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Az-Zumar",
      },
    ],
    "id": "39",
    "unicode": "&#100;",
  },
  {
    "name": "غافر",
    "number": 40,
    "numberOfAyahs": 85,
    "hasBismillah": true,
    "queryIndexes": [
      "40",
      "the forgiver",
      "forgiver",
      "the",
      "غافر",
      "ghafir",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 60,
    },
    "slug": "ghafir",
    "translations": [
      {
        "language": "en",
        "text": "The Forgiver",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Ghafir",
      },
    ],
    "id": "40",
    "unicode": "&#68;",
  },
  {
    "name": "فصلت",
    "number": 41,
    "numberOfAyahs": 54,
    "hasBismillah": true,
    "queryIndexes": [
      "41",
      "explained in detail",
      "in detail",
      "detail",
      "explained",
      "in",
      "فصلت",
      "fussilat",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 61,
    },
    "slug": "fussilat",
    "translations": [
      {
        "language": "en",
        "text": "Explained in Detail",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Fussilat",
      },
    ],
    "id": "41",
    "unicode": "&#69;",
  },
  {
    "name": "الشورى",
    "number": 42,
    "numberOfAyahs": 53,
    "hasBismillah": true,
    "queryIndexes": [
      "42",
      "the consultation",
      "consultation",
      "the",
      "الشورى",
      "ash shuraa",
      "shuraa",
      "ash",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 62,
    },
    "slug": "ash-shuraa",
    "translations": [
      {
        "language": "en",
        "text": "The Consultation",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Ash-Shuraa",
      },
    ],
    "id": "42",
    "unicode": "&#101;",
  },
  {
    "name": "الزخرف",
    "number": 43,
    "numberOfAyahs": 89,
    "hasBismillah": true,
    "queryIndexes": [
      "43",
      "the ornaments of gold",
      "ornaments of gold",
      "of gold",
      "gold",
      "the",
      "ornaments",
      "of",
      "الزخرف",
      "az zukhruf",
      "zukhruf",
      "az",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 63,
    },
    "slug": "az-zukhruf",
    "translations": [
      {
        "language": "en",
        "text": "The Ornaments of Gold",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Az-Zukhruf",
      },
    ],
    "id": "43",
    "unicode": "&#70;",
  },
  {
    "name": "الدخان",
    "number": 44,
    "numberOfAyahs": 59,
    "hasBismillah": true,
    "queryIndexes": [
      "44",
      "the smoke",
      "smoke",
      "the",
      "الدخان",
      "ad dukhan",
      "dukhan",
      "ad",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 64,
    },
    "slug": "ad-dukhan",
    "translations": [
      {
        "language": "en",
        "text": "The Smoke",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Ad-Dukhan",
      },
    ],
    "id": "44",
    "unicode": "&#102;",
  },
  {
    "name": "الجاثية",
    "number": 45,
    "numberOfAyahs": 37,
    "hasBismillah": true,
    "queryIndexes": [
      "45",
      "the crouching",
      "crouching",
      "the",
      "الجاثية",
      "al jathiyah",
      "jathiyah",
      "al",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 65,
    },
    "slug": "al-jathiyah",
    "translations": [
      {
        "language": "en",
        "text": "The Crouching",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Al-Jathiyah",
      },
    ],
    "id": "45",
    "unicode": "&#103;",
  },
  {
    "name": "الأحقاف",
    "number": 46,
    "numberOfAyahs": 35,
    "hasBismillah": true,
    "queryIndexes": [
      "46",
      "the wind curved sandhills",
      "wind curved sandhills",
      "curved sandhills",
      "sandhills",
      "the",
      "wind",
      "curved",
      "الأحقاف",
      "al ahqaf",
      "ahqaf",
      "al",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 66,
    },
    "slug": "al-ahqaf",
    "translations": [
      {
        "language": "en",
        "text": "The Wind-Curved Sandhills",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Al-Ahqaf",
      },
    ],
    "id": "46",
    "unicode": "&#71;",
  },
  {
    "name": "محمد",
    "number": 47,
    "numberOfAyahs": 38,
    "hasBismillah": true,
    "queryIndexes": [
      "47",
      "muhammad",
      "محمد",
      "muhammad",
      "madinah",
      "medinan",
      "medinah",
    ],
    "revelation": {
      "place": "medinan",
      "order": 95,
    },
    "slug": "muhammad",
    "translations": [
      {
        "language": "en",
        "text": "Muhammad",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Muhammad",
      },
    ],
    "id": "47",
    "unicode": "&#72;",
  },
  {
    "name": "الفتح",
    "number": 48,
    "numberOfAyahs": 29,
    "hasBismillah": true,
    "queryIndexes": [
      "48",
      "the victory",
      "victory",
      "the",
      "الفتح",
      "al fath",
      "fath",
      "al",
      "madinah",
      "medinan",
      "medinah",
    ],
    "revelation": {
      "place": "medinan",
      "order": 111,
    },
    "slug": "al-fath",
    "translations": [
      {
        "language": "en",
        "text": "The Victory",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Al-Fath",
      },
    ],
    "id": "48",
    "unicode": "&#104;",
  },
  {
    "name": "الحجرات",
    "number": 49,
    "numberOfAyahs": 18,
    "hasBismillah": true,
    "queryIndexes": [
      "49",
      "the rooms",
      "rooms",
      "the",
      "الحجرات",
      "al hujurat",
      "hujurat",
      "al",
      "madinah",
      "medinan",
      "medinah",
    ],
    "revelation": {
      "place": "medinan",
      "order": 106,
    },
    "slug": "al-hujurat",
    "translations": [
      {
        "language": "en",
        "text": "The Rooms",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Al-Hujurat",
      },
    ],
    "id": "49",
    "unicode": "&#73;",
  },
  {
    "name": "ق",
    "number": 50,
    "numberOfAyahs": 45,
    "hasBismillah": true,
    "queryIndexes": [
      "50",
      "the letter \"qaf\"",
      "letter \"qaf\"",
      "\"qaf\"",
      "the",
      "letter",
      "ق",
      "qaf",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 34,
    },
    "slug": "qaf",
    "translations": [
      {
        "language": "en",
        "text": "The Letter \"Qaf\"",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Qaf",
      },
    ],
    "id": "50",
    "unicode": "&#105;",
  },
  {
    "name": "الذاريات",
    "number": 51,
    "numberOfAyahs": 60,
    "hasBismillah": true,
    "queryIndexes": [
      "51",
      "the winnowing winds",
      "winnowing winds",
      "winds",
      "the",
      "winnowing",
      "الذاريات",
      "adh dhariyat",
      "dhariyat",
      "adh",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 67,
    },
    "slug": "adh-dhariyat",
    "translations": [
      {
        "language": "en",
        "text": "The Winnowing Winds",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Adh-Dhariyat",
      },
    ],
    "id": "51",
    "unicode": "&#74;",
  },
  {
    "name": "الطور",
    "number": 52,
    "numberOfAyahs": 49,
    "hasBismillah": true,
    "queryIndexes": [
      "52",
      "the mount",
      "mount",
      "the",
      "الطور",
      "at tur",
      "tur",
      "at",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 76,
    },
    "slug": "at-tur",
    "translations": [
      {
        "language": "en",
        "text": "The Mount",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "At-Tur",
      },
    ],
    "id": "52",
    "unicode": "&#106;",
  },
  {
    "name": "النجم",
    "number": 53,
    "numberOfAyahs": 62,
    "hasBismillah": true,
    "queryIndexes": [
      "53",
      "the star",
      "star",
      "the",
      "النجم",
      "an najm",
      "najm",
      "an",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 23,
    },
    "slug": "an-najm",
    "translations": [
      {
        "language": "en",
        "text": "The Star",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "An-Najm",
      },
    ],
    "id": "53",
    "unicode": "&#75;",
  },
  {
    "name": "القمر",
    "number": 54,
    "numberOfAyahs": 55,
    "hasBismillah": true,
    "queryIndexes": [
      "54",
      "the moon",
      "moon",
      "the",
      "القمر",
      "al qamar",
      "qamar",
      "al",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 37,
    },
    "slug": "al-qamar",
    "translations": [
      {
        "language": "en",
        "text": "The Moon",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Al-Qamar",
      },
    ],
    "id": "54",
    "unicode": "&#107;",
  },
  {
    "name": "الرحمن",
    "number": 55,
    "numberOfAyahs": 78,
    "hasBismillah": true,
    "queryIndexes": [
      "55",
      "the beneficent",
      "beneficent",
      "the",
      "الرحمن",
      "ar rahman",
      "rahman",
      "ar",
      "madinah",
      "medinan",
      "medinah",
    ],
    "revelation": {
      "place": "medinan",
      "order": 97,
    },
    "slug": "ar-rahman",
    "translations": [
      {
        "language": "en",
        "text": "The Beneficent",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Ar-Rahman",
      },
    ],
    "id": "55",
    "unicode": "&#108;",
  },
  {
    "name": "الواقعة",
    "number": 56,
    "numberOfAyahs": 96,
    "hasBismillah": true,
    "queryIndexes": [
      "56",
      "the inevitable",
      "inevitable",
      "the",
      "الواقعة",
      "al waqi'ah",
      "waqi'ah",
      "al",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 46,
    },
    "slug": "al-waqiah",
    "translations": [
      {
        "language": "en",
        "text": "The Inevitable",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Al-Waqi'ah",
      },
    ],
    "id": "56",
    "unicode": "&#76;",
  },
  {
    "name": "الحديد",
    "number": 57,
    "numberOfAyahs": 29,
    "hasBismillah": true,
    "queryIndexes": [
      "57",
      "the iron",
      "iron",
      "the",
      "الحديد",
      "al hadid",
      "hadid",
      "al",
      "madinah",
      "medinan",
      "medinah",
    ],
    "revelation": {
      "place": "medinan",
      "order": 94,
    },
    "slug": "al-hadid",
    "translations": [
      {
        "language": "en",
        "text": "The Iron",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Al-Hadid",
      },
    ],
    "id": "57",
    "unicode": "&#77;",
  },
  {
    "name": "المجادلة",
    "number": 58,
    "numberOfAyahs": 22,
    "hasBismillah": true,
    "queryIndexes": [
      "58",
      "the pleading woman",
      "pleading woman",
      "woman",
      "the",
      "pleading",
      "المجادلة",
      "al mujadila",
      "mujadila",
      "al",
      "madinah",
      "medinan",
      "medinah",
    ],
    "revelation": {
      "place": "medinan",
      "order": 105,
    },
    "slug": "al-mujadila",
    "translations": [
      {
        "language": "en",
        "text": "The Pleading Woman",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Al-Mujadila",
      },
    ],
    "id": "58",
    "unicode": "&#109;",
  },
  {
    "name": "الحشر",
    "number": 59,
    "numberOfAyahs": 24,
    "hasBismillah": true,
    "queryIndexes": [
      "59",
      "the exile",
      "exile",
      "the",
      "الحشر",
      "al hashr",
      "hashr",
      "al",
      "madinah",
      "medinan",
      "medinah",
    ],
    "revelation": {
      "place": "medinan",
      "order": 101,
    },
    "slug": "al-hashr",
    "translations": [
      {
        "language": "en",
        "text": "The Exile",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Al-Hashr",
      },
    ],
    "id": "59",
    "unicode": "&#110;",
  },
  {
    "name": "الممتحنة",
    "number": 60,
    "numberOfAyahs": 13,
    "hasBismillah": true,
    "queryIndexes": [
      "60",
      "she that is to be examined",
      "that is to be examined",
      "is to be examined",
      "to be examined",
      "be examined",
      "examined",
      "she",
      "that",
      "is",
      "to",
      "be",
      "الممتحنة",
      "al mumtahanah",
      "mumtahanah",
      "al",
      "madinah",
      "medinan",
      "medinah",
    ],
    "revelation": {
      "place": "medinan",
      "order": 91,
    },
    "slug": "al-mumtahanah",
    "translations": [
      {
        "language": "en",
        "text": "She that is to be examined",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Al-Mumtahanah",
      },
    ],
    "id": "60",
    "unicode": "&#78;",
  },
  {
    "name": "الصف",
    "number": 61,
    "numberOfAyahs": 14,
    "hasBismillah": true,
    "queryIndexes": [
      "61",
      "the ranks",
      "ranks",
      "the",
      "الصف",
      "as saf",
      "saf",
      "as",
      "madinah",
      "medinan",
      "medinah",
    ],
    "revelation": {
      "place": "medinan",
      "order": 109,
    },
    "slug": "as-saf",
    "translations": [
      {
        "language": "en",
        "text": "The Ranks",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "As-Saf",
      },
    ],
    "id": "61",
    "unicode": "&#79;",
  },
  {
    "name": "الجمعة",
    "number": 62,
    "numberOfAyahs": 11,
    "hasBismillah": true,
    "queryIndexes": [
      "62",
      "the congregation, friday",
      "congregation, friday",
      "friday",
      "the",
      "congregation,",
      "الجمعة",
      "al jumu'ah",
      "jumu'ah",
      "al",
      "madinah",
      "medinan",
      "medinah",
    ],
    "revelation": {
      "place": "medinan",
      "order": 110,
    },
    "slug": "al-jumah",
    "translations": [
      {
        "language": "en",
        "text": "The Congregation, Friday",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Al-Jumu'ah",
      },
    ],
    "id": "62",
    "unicode": "&#111;",
  },
  {
    "name": "المنافقون",
    "number": 63,
    "numberOfAyahs": 11,
    "hasBismillah": true,
    "queryIndexes": [
      "63",
      "the hypocrites",
      "hypocrites",
      "the",
      "المنافقون",
      "al munafiqun",
      "munafiqun",
      "al",
      "madinah",
      "medinan",
      "medinah",
    ],
    "revelation": {
      "place": "medinan",
      "order": 104,
    },
    "slug": "al-munaifqun",
    "translations": [
      {
        "language": "en",
        "text": "The Hypocrites",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Al-Munafiqun",
      },
    ],
    "id": "63",
    "unicode": "&#112;",
  },
  {
    "name": "التغابن",
    "number": 64,
    "numberOfAyahs": 18,
    "hasBismillah": true,
    "queryIndexes": [
      "64",
      "the mutual disillusion",
      "mutual disillusion",
      "disillusion",
      "the",
      "mutual",
      "التغابن",
      "at taghabun",
      "taghabun",
      "at",
      "madinah",
      "medinan",
      "medinah",
    ],
    "revelation": {
      "place": "medinan",
      "order": 108,
    },
    "slug": "at-taghabun",
    "translations": [
      {
        "language": "en",
        "text": "The Mutual Disillusion",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "At-Taghabun",
      },
    ],
    "id": "64",
    "unicode": "&#80;",
  },
  {
    "name": "الطلاق",
    "number": 65,
    "numberOfAyahs": 12,
    "hasBismillah": true,
    "queryIndexes": [
      "65",
      "the divorce",
      "divorce",
      "the",
      "الطلاق",
      "at talaq",
      "talaq",
      "at",
      "madinah",
      "medinan",
      "medinah",
    ],
    "revelation": {
      "place": "medinan",
      "order": 99,
    },
    "slug": "at-talaq",
    "translations": [
      {
        "language": "en",
        "text": "The Divorce",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "At-Talaq",
      },
    ],
    "id": "65",
    "unicode": "&#81;",
  },
  {
    "name": "التحريم",
    "number": 66,
    "numberOfAyahs": 12,
    "hasBismillah": true,
    "queryIndexes": [
      "66",
      "the prohibtiion",
      "prohibtiion",
      "the",
      "التحريم",
      "at tahrim",
      "tahrim",
      "at",
      "madinah",
      "medinan",
      "medinah",
    ],
    "revelation": {
      "place": "medinan",
      "order": 107,
    },
    "slug": "at-tahrim",
    "translations": [
      {
        "language": "en",
        "text": "The Prohibtiion",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "At-Tahrim",
      },
    ],
    "id": "66",
    "unicode": "&#113;",
  },
  {
    "name": "الملك",
    "number": 67,
    "numberOfAyahs": 30,
    "hasBismillah": true,
    "queryIndexes": [
      "67",
      "the sovereignty",
      "sovereignty",
      "the",
      "الملك",
      "al mulk",
      "mulk",
      "al",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 77,
    },
    "slug": "al-mulk",
    "translations": [
      {
        "language": "en",
        "text": "The Sovereignty",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Al-Mulk",
      },
    ],
    "id": "67",
    "unicode": "&#82;",
  },
  {
    "name": "القلم",
    "number": 68,
    "numberOfAyahs": 52,
    "hasBismillah": true,
    "queryIndexes": [
      "68",
      "the pen",
      "pen",
      "the",
      "القلم",
      "al qalam",
      "qalam",
      "al",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 2,
    },
    "slug": "at-qalam",
    "translations": [
      {
        "language": "en",
        "text": "The Pen",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Al-Qalam",
      },
    ],
    "id": "68",
    "unicode": "&#114;",
  },
  {
    "name": "الحاقة",
    "number": 69,
    "numberOfAyahs": 52,
    "hasBismillah": true,
    "queryIndexes": [
      "69",
      "the reality",
      "reality",
      "the",
      "الحاقة",
      "al haqqah",
      "haqqah",
      "al",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 78,
    },
    "slug": "at-haqqah",
    "translations": [
      {
        "language": "en",
        "text": "The Reality",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Al-Haqqah",
      },
    ],
    "id": "69",
    "unicode": "&#115;",
  },
  {
    "name": "المعارج",
    "number": 70,
    "numberOfAyahs": 44,
    "hasBismillah": true,
    "queryIndexes": [
      "70",
      "the ascending stairways",
      "ascending stairways",
      "stairways",
      "the",
      "ascending",
      "المعارج",
      "al ma'arij",
      "ma'arij",
      "al",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 79,
    },
    "slug": "at-maarij",
    "translations": [
      {
        "language": "en",
        "text": "The Ascending Stairways",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Al-Ma'arij",
      },
    ],
    "id": "70",
    "unicode": "&#83;",
  },
  {
    "name": "نوح",
    "number": 71,
    "numberOfAyahs": 28,
    "hasBismillah": true,
    "queryIndexes": [
      "71",
      "noah",
      "نوح",
      "nuh",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 71,
    },
    "slug": "nuh",
    "translations": [
      {
        "language": "en",
        "text": "Noah",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Nuh",
      },
    ],
    "id": "71",
    "unicode": "&#116;",
  },
  {
    "name": "الجن",
    "number": 72,
    "numberOfAyahs": 28,
    "hasBismillah": true,
    "queryIndexes": [
      "72",
      "the jinn",
      "jinn",
      "the",
      "الجن",
      "al jinn",
      "jinn",
      "al",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 40,
    },
    "slug": "al-jinn",
    "translations": [
      {
        "language": "en",
        "text": "The Jinn",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Al-Jinn",
      },
    ],
    "id": "72",
    "unicode": "&#84;",
  },
  {
    "name": "المزمل",
    "number": 73,
    "numberOfAyahs": 20,
    "hasBismillah": true,
    "queryIndexes": [
      "73",
      "the enshrouded one",
      "enshrouded one",
      "one",
      "the",
      "enshrouded",
      "المزمل",
      "al muzzammil",
      "muzzammil",
      "al",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 3,
    },
    "slug": "al-muzzammil",
    "translations": [
      {
        "language": "en",
        "text": "The Enshrouded One",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Al-Muzzammil",
      },
    ],
    "id": "73",
    "unicode": "&#117;",
  },
  {
    "name": "المدثر",
    "number": 74,
    "numberOfAyahs": 56,
    "hasBismillah": true,
    "queryIndexes": [
      "74",
      "the cloaked one",
      "cloaked one",
      "one",
      "the",
      "cloaked",
      "المدثر",
      "al muddaththir",
      "muddaththir",
      "al",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 4,
    },
    "slug": "al-muddaththir",
    "translations": [
      {
        "language": "en",
        "text": "The Cloaked One",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Al-Muddaththir",
      },
    ],
    "id": "74",
    "unicode": "&#85;",
  },
  {
    "name": "القيامة",
    "number": 75,
    "numberOfAyahs": 40,
    "hasBismillah": true,
    "queryIndexes": [
      "75",
      "the resurrection",
      "resurrection",
      "the",
      "القيامة",
      "al qiyamah",
      "qiyamah",
      "al",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 31,
    },
    "slug": "al-qiyamah",
    "translations": [
      {
        "language": "en",
        "text": "The Resurrection",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Al-Qiyamah",
      },
    ],
    "id": "75",
    "unicode": "&#118;",
  },
  {
    "name": "الانسان",
    "number": 76,
    "numberOfAyahs": 31,
    "hasBismillah": true,
    "queryIndexes": [
      "76",
      "the man",
      "man",
      "the",
      "الانسان",
      "al insan",
      "insan",
      "al",
      "madinah",
      "medinan",
      "medinah",
    ],
    "revelation": {
      "place": "medinan",
      "order": 98,
    },
    "slug": "al-insan",
    "translations": [
      {
        "language": "en",
        "text": "The Man",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Al-Insan",
      },
    ],
    "id": "76",
    "unicode": "&#86;",
  },
  {
    "name": "المرسلات",
    "number": 77,
    "numberOfAyahs": 50,
    "hasBismillah": true,
    "queryIndexes": [
      "77",
      "the emissaries",
      "emissaries",
      "the",
      "المرسلات",
      "al mursalat",
      "mursalat",
      "al",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 33,
    },
    "slug": "al-mursalat",
    "translations": [
      {
        "language": "en",
        "text": "The Emissaries",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Al-Mursalat",
      },
    ],
    "id": "77",
    "unicode": "&#87;",
  },
  {
    "name": "النبإ",
    "number": 78,
    "numberOfAyahs": 40,
    "hasBismillah": true,
    "queryIndexes": [
      "78",
      "the tidings",
      "tidings",
      "the",
      "النبإ",
      "an naba",
      "naba",
      "an",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 80,
    },
    "slug": "an-naba",
    "translations": [
      {
        "language": "en",
        "text": "The Tidings",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "An-Naba",
      },
    ],
    "id": "78",
    "unicode": "&#119;",
  },
  {
    "name": "النازعات",
    "number": 79,
    "numberOfAyahs": 46,
    "hasBismillah": true,
    "queryIndexes": [
      "79",
      "those who drag forth",
      "who drag forth",
      "drag forth",
      "forth",
      "those",
      "who",
      "drag",
      "النازعات",
      "an nazi'at",
      "nazi'at",
      "an",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 81,
    },
    "slug": "an-naziat",
    "translations": [
      {
        "language": "en",
        "text": "Those who drag forth",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "An-Nazi'at",
      },
    ],
    "id": "79",
    "unicode": "&#120;",
  },
  {
    "name": "عبس",
    "number": 80,
    "numberOfAyahs": 42,
    "hasBismillah": true,
    "queryIndexes": [
      "80",
      "he frowned",
      "frowned",
      "he",
      "عبس",
      "'abasa",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 24,
    },
    "slug": "abasa",
    "translations": [
      {
        "language": "en",
        "text": "He Frowned",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "'Abasa",
      },
    ],
    "id": "80",
    "unicode": "&#88;",
  },
  {
    "name": "التكوير",
    "number": 81,
    "numberOfAyahs": 29,
    "hasBismillah": true,
    "queryIndexes": [
      "81",
      "the overthrowing",
      "overthrowing",
      "the",
      "التكوير",
      "at takwir",
      "takwir",
      "at",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 7,
    },
    "slug": "at-takwir",
    "translations": [
      {
        "language": "en",
        "text": "The Overthrowing",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "At-Takwir",
      },
    ],
    "id": "81",
    "unicode": "&#121;",
  },
  {
    "name": "الإنفطار",
    "number": 82,
    "numberOfAyahs": 19,
    "hasBismillah": true,
    "queryIndexes": [
      "82",
      "the cleaving",
      "cleaving",
      "the",
      "الإنفطار",
      "al infitar",
      "infitar",
      "al",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 82,
    },
    "slug": "al-infitar",
    "translations": [
      {
        "language": "en",
        "text": "The Cleaving",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Al-Infitar",
      },
    ],
    "id": "82",
    "unicode": "&#89;",
  },
  {
    "name": "المطففين",
    "number": 83,
    "numberOfAyahs": 36,
    "hasBismillah": true,
    "queryIndexes": [
      "83",
      "the defrauding",
      "defrauding",
      "the",
      "المطففين",
      "al mutaffifin",
      "mutaffifin",
      "al",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 86,
    },
    "slug": "al-mutaffifin",
    "translations": [
      {
        "language": "en",
        "text": "The Defrauding",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Al-Mutaffifin",
      },
    ],
    "id": "83",
    "unicode": "&#90;",
  },
  {
    "name": "الإنشقاق",
    "number": 84,
    "numberOfAyahs": 25,
    "hasBismillah": true,
    "queryIndexes": [
      "84",
      "the sundering",
      "sundering",
      "the",
      "الإنشقاق",
      "al inshiqaq",
      "inshiqaq",
      "al",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 83,
    },
    "slug": "al-inshiqaq",
    "translations": [
      {
        "language": "en",
        "text": "The Sundering",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Al-Inshiqaq",
      },
    ],
    "id": "84",
    "unicode": "&#122;",
  },
  {
    "name": "البروج",
    "number": 85,
    "numberOfAyahs": 22,
    "hasBismillah": true,
    "queryIndexes": [
      "85",
      "the mansions of the stars",
      "mansions of the stars",
      "of the stars",
      "the stars",
      "stars",
      "the",
      "mansions",
      "of",
      "البروج",
      "al buruj",
      "buruj",
      "al",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 27,
    },
    "slug": "al-buruj",
    "translations": [
      {
        "language": "en",
        "text": "The Mansions of the Stars",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Al-Buruj",
      },
    ],
    "id": "85",
    "unicode": "&#91;",
  },
  {
    "name": "الطارق",
    "number": 86,
    "numberOfAyahs": 17,
    "hasBismillah": true,
    "queryIndexes": [
      "86",
      "the nightcommer",
      "nightcommer",
      "the",
      "الطارق",
      "at tariq",
      "tariq",
      "at",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 36,
    },
    "slug": "at-tariq",
    "translations": [
      {
        "language": "en",
        "text": "The Nightcommer",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "At-Tariq",
      },
    ],
    "id": "86",
    "unicode": "&#92;",
  },
  {
    "name": "الأعلى",
    "number": 87,
    "numberOfAyahs": 19,
    "hasBismillah": true,
    "queryIndexes": [
      "87",
      "the most high",
      "most high",
      "high",
      "the",
      "most",
      "الأعلى",
      "al a'la",
      "a'la",
      "al",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 8,
    },
    "slug": "al-ala",
    "translations": [
      {
        "language": "en",
        "text": "The Most High",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Al-A'la",
      },
    ],
    "id": "87",
    "unicode": "&#93;",
  },
  {
    "name": "الغاشية",
    "number": 88,
    "numberOfAyahs": 26,
    "hasBismillah": true,
    "queryIndexes": [
      "88",
      "the overwhelming",
      "overwhelming",
      "the",
      "الغاشية",
      "al ghashiyah",
      "ghashiyah",
      "al",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 68,
    },
    "slug": "al-ghashiyah",
    "translations": [
      {
        "language": "en",
        "text": "The Overwhelming",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Al-Ghashiyah",
      },
    ],
    "id": "88",
    "unicode": "&#94;",
  },
  {
    "name": "الفجر",
    "number": 89,
    "numberOfAyahs": 30,
    "hasBismillah": true,
    "queryIndexes": [
      "89",
      "the dawn",
      "dawn",
      "the",
      "الفجر",
      "al fajr",
      "fajr",
      "al",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 10,
    },
    "slug": "al-fajr",
    "translations": [
      {
        "language": "en",
        "text": "The Dawn",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Al-Fajr",
      },
    ],
    "id": "89",
    "unicode": "&#95;",
  },
  {
    "name": "البلد",
    "number": 90,
    "numberOfAyahs": 20,
    "hasBismillah": true,
    "queryIndexes": [
      "90",
      "the city",
      "city",
      "the",
      "البلد",
      "al balad",
      "balad",
      "al",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 35,
    },
    "slug": "al-balad",
    "translations": [
      {
        "language": "en",
        "text": "The City",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Al-Balad",
      },
    ],
    "id": "90",
    "unicode": "&#96;",
  },
  {
    "name": "الشمس",
    "number": 91,
    "numberOfAyahs": 15,
    "hasBismillah": true,
    "queryIndexes": [
      "91",
      "the sun",
      "sun",
      "the",
      "الشمس",
      "ash shams",
      "shams",
      "ash",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 26,
    },
    "slug": "ash-shams",
    "translations": [
      {
        "language": "en",
        "text": "The Sun",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Ash-Shams",
      },
    ],
    "id": "91",
    "unicode": "&#123;",
  },
  {
    "name": "الليل",
    "number": 92,
    "numberOfAyahs": 21,
    "hasBismillah": true,
    "queryIndexes": [
      "92",
      "the night",
      "night",
      "the",
      "الليل",
      "al layl",
      "layl",
      "al",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 9,
    },
    "slug": "al-layl",
    "translations": [
      {
        "language": "en",
        "text": "The Night",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Al-Layl",
      },
    ],
    "id": "92",
    "unicode": "&#124;",
  },
  {
    "name": "الضحى",
    "number": 93,
    "numberOfAyahs": 11,
    "hasBismillah": true,
    "queryIndexes": [
      "93",
      "the morning hours",
      "morning hours",
      "hours",
      "the",
      "morning",
      "الضحى",
      "ad duhaa",
      "duhaa",
      "ad",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 11,
    },
    "slug": "ad-duhaa",
    "translations": [
      {
        "language": "en",
        "text": "The Morning Hours",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Ad-Duhaa",
      },
    ],
    "id": "93",
    "unicode": "&#125;",
  },
  {
    "name": "الشرح",
    "number": 94,
    "numberOfAyahs": 8,
    "hasBismillah": true,
    "queryIndexes": [
      "94",
      "the relief",
      "relief",
      "the",
      "الشرح",
      "ash sharh",
      "sharh",
      "ash",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 12,
    },
    "slug": "ash-sharh",
    "translations": [
      {
        "language": "en",
        "text": "The Relief",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Ash-Sharh",
      },
    ],
    "id": "94",
    "unicode": "&#126;",
  },
  {
    "name": "التين",
    "number": 95,
    "numberOfAyahs": 8,
    "hasBismillah": true,
    "queryIndexes": [
      "95",
      "the fig",
      "fig",
      "the",
      "التين",
      "at tin",
      "tin",
      "at",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 28,
    },
    "slug": "at-tin",
    "translations": [
      {
        "language": "en",
        "text": "The Fig",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "At-Tin",
      },
    ],
    "id": "95",
    "unicode": "&#161;",
  },
  {
    "name": "العلق",
    "number": 96,
    "numberOfAyahs": 19,
    "hasBismillah": true,
    "queryIndexes": [
      "96",
      "the clot",
      "clot",
      "the",
      "العلق",
      "al 'alaq",
      "'alaq",
      "al",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 1,
    },
    "slug": "al-alaq",
    "translations": [
      {
        "language": "en",
        "text": "The Clot",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Al-'Alaq",
      },
    ],
    "id": "96",
    "unicode": "&#162;",
  },
  {
    "name": "القدر",
    "number": 97,
    "numberOfAyahs": 5,
    "hasBismillah": true,
    "queryIndexes": [
      "97",
      "the power",
      "power",
      "the",
      "القدر",
      "al qadr",
      "qadr",
      "al",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 25,
    },
    "slug": "al-qadr",
    "translations": [
      {
        "language": "en",
        "text": "The Power",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Al-Qadr",
      },
    ],
    "id": "97",
    "unicode": "&#163;",
  },
  {
    "name": "البينة",
    "number": 98,
    "numberOfAyahs": 8,
    "hasBismillah": true,
    "queryIndexes": [
      "98",
      "the clear proof",
      "clear proof",
      "proof",
      "the",
      "clear",
      "البينة",
      "al bayyinah",
      "bayyinah",
      "al",
      "madinah",
      "medinan",
      "medinah",
    ],
    "revelation": {
      "place": "medinan",
      "order": 100,
    },
    "slug": "al-bayyinah",
    "translations": [
      {
        "language": "en",
        "text": "The Clear Proof",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Al-Bayyinah",
      },
    ],
    "id": "98",
    "unicode": "&#164;",
  },
  {
    "name": "الزلزلة",
    "number": 99,
    "numberOfAyahs": 8,
    "hasBismillah": true,
    "queryIndexes": [
      "99",
      "the earthquake",
      "earthquake",
      "the",
      "الزلزلة",
      "az zalzalah",
      "zalzalah",
      "az",
      "madinah",
      "medinan",
      "medinah",
    ],
    "revelation": {
      "place": "medinan",
      "order": 93,
    },
    "slug": "az-zalzalah",
    "translations": [
      {
        "language": "en",
        "text": "The Earthquake",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Az-Zalzalah",
      },
    ],
    "id": "99",
    "unicode": "&#165;",
  },
  {
    "name": "العاديات",
    "number": 100,
    "numberOfAyahs": 11,
    "hasBismillah": true,
    "queryIndexes": [
      "100",
      "the courser",
      "courser",
      "the",
      "العاديات",
      "al 'adiyat",
      "'adiyat",
      "al",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 14,
    },
    "slug": "al-adiyat",
    "translations": [
      {
        "language": "en",
        "text": "The Courser",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Al-'Adiyat",
      },
    ],
    "id": "100",
    "unicode": "&#166;",
  },
  {
    "name": "القارعة",
    "number": 101,
    "numberOfAyahs": 11,
    "hasBismillah": true,
    "queryIndexes": [
      "101",
      "the calamity",
      "calamity",
      "the",
      "القارعة",
      "al qari'ah",
      "qari'ah",
      "al",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 30,
    },
    "slug": "al-qariah",
    "translations": [
      {
        "language": "en",
        "text": "The Calamity",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Al-Qari'ah",
      },
    ],
    "id": "101",
    "unicode": "&#167;",
  },
  {
    "name": "التكاثر",
    "number": 102,
    "numberOfAyahs": 8,
    "hasBismillah": true,
    "queryIndexes": [
      "102",
      "the rivalry in world increase",
      "rivalry in world increase",
      "in world increase",
      "world increase",
      "increase",
      "the",
      "rivalry",
      "in",
      "world",
      "التكاثر",
      "at takathur",
      "takathur",
      "at",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 16,
    },
    "slug": "at-takathur",
    "translations": [
      {
        "language": "en",
        "text": "The Rivalry in world increase",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "At-Takathur",
      },
    ],
    "id": "102",
    "unicode": "&#168;",
  },
  {
    "name": "العصر",
    "number": 103,
    "numberOfAyahs": 3,
    "hasBismillah": true,
    "queryIndexes": [
      "103",
      "the declining day",
      "declining day",
      "day",
      "the",
      "declining",
      "العصر",
      "al 'asr",
      "'asr",
      "al",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 13,
    },
    "slug": "al-asr",
    "translations": [
      {
        "language": "en",
        "text": "The Declining Day",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Al-'Asr",
      },
    ],
    "id": "103",
    "unicode": "&#169;",
  },
  {
    "name": "الهمزة",
    "number": 104,
    "numberOfAyahs": 9,
    "hasBismillah": true,
    "queryIndexes": [
      "104",
      "the traducer",
      "traducer",
      "the",
      "الهمزة",
      "al humazah",
      "humazah",
      "al",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 32,
    },
    "slug": "al-humazah",
    "translations": [
      {
        "language": "en",
        "text": "The Traducer",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Al-Humazah",
      },
    ],
    "id": "104",
    "unicode": "&#170;",
  },
  {
    "name": "الفيل",
    "number": 105,
    "numberOfAyahs": 5,
    "hasBismillah": true,
    "queryIndexes": [
      "105",
      "the elephant",
      "elephant",
      "the",
      "الفيل",
      "al fil",
      "fil",
      "al",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 19,
    },
    "slug": "al-fil",
    "translations": [
      {
        "language": "en",
        "text": "The Elephant",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Al-Fil",
      },
    ],
    "id": "105",
    "unicode": "&#171;",
  },
  {
    "name": "قريش",
    "number": 106,
    "numberOfAyahs": 4,
    "hasBismillah": true,
    "queryIndexes": [
      "106",
      "quraysh",
      "قريش",
      "quraysh",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 29,
    },
    "slug": "quraysh",
    "translations": [
      {
        "language": "en",
        "text": "Quraysh",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Quraysh",
      },
    ],
    "id": "106",
    "unicode": "&#172;",
  },
  {
    "name": "الماعون",
    "number": 107,
    "numberOfAyahs": 7,
    "hasBismillah": true,
    "queryIndexes": [
      "107",
      "the small kindesses",
      "small kindesses",
      "kindesses",
      "the",
      "small",
      "الماعون",
      "al ma'un",
      "ma'un",
      "al",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 17,
    },
    "slug": "al-maun",
    "translations": [
      {
        "language": "en",
        "text": "The Small Kindesses",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Al-Ma'un",
      },
    ],
    "id": "107",
    "unicode": "&#174;",
  },
  {
    "name": "الكوثر",
    "number": 108,
    "numberOfAyahs": 3,
    "hasBismillah": true,
    "queryIndexes": [
      "108",
      "the abundance",
      "abundance",
      "the",
      "الكوثر",
      "al kawthar",
      "kawthar",
      "al",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 15,
    },
    "slug": "al-kawthar",
    "translations": [
      {
        "language": "en",
        "text": "The Abundance",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Al-Kawthar",
      },
    ],
    "id": "108",
    "unicode": "&#175;",
  },
  {
    "name": "الكافرون",
    "number": 109,
    "numberOfAyahs": 6,
    "hasBismillah": true,
    "queryIndexes": [
      "109",
      "the disbelievers",
      "disbelievers",
      "the",
      "الكافرون",
      "al kafirun",
      "kafirun",
      "al",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 18,
    },
    "slug": "al-kafirun",
    "translations": [
      {
        "language": "en",
        "text": "The Disbelievers",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Al-Kafirun",
      },
    ],
    "id": "109",
    "unicode": "&#176;",
  },
  {
    "name": "النصر",
    "number": 110,
    "numberOfAyahs": 3,
    "hasBismillah": true,
    "queryIndexes": [
      "110",
      "the divine support",
      "divine support",
      "support",
      "the",
      "divine",
      "النصر",
      "an nasr",
      "nasr",
      "an",
      "madinah",
      "medinan",
      "medinah",
    ],
    "revelation": {
      "place": "medinan",
      "order": 114,
    },
    "slug": "an-nasr",
    "translations": [
      {
        "language": "en",
        "text": "The Divine Support",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "An-Nasr",
      },
    ],
    "id": "110",
    "unicode": "&#177;",
  },
  {
    "name": "المسد",
    "number": 111,
    "numberOfAyahs": 5,
    "hasBismillah": true,
    "queryIndexes": [
      "111",
      "the palm fiber",
      "palm fiber",
      "fiber",
      "the",
      "palm",
      "المسد",
      "al masad",
      "masad",
      "al",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 6,
    },
    "slug": "al-masad",
    "translations": [
      {
        "language": "en",
        "text": "The Palm Fiber",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Al-Masad",
      },
    ],
    "id": "111",
    "unicode": "&#178;",
  },
  {
    "name": "الإخلاص",
    "number": 112,
    "numberOfAyahs": 4,
    "hasBismillah": true,
    "queryIndexes": [
      "112",
      "the sincerity",
      "sincerity",
      "the",
      "الإخلاص",
      "al ikhlas",
      "ikhlas",
      "al",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 22,
    },
    "slug": "al-ikhlas",
    "translations": [
      {
        "language": "en",
        "text": "The Sincerity",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Al-Ikhlas",
      },
    ],
    "id": "112",
    "unicode": "&#179;",
  },
  {
    "name": "الفلق",
    "number": 113,
    "numberOfAyahs": 5,
    "hasBismillah": true,
    "queryIndexes": [
      "113",
      "the daybreak",
      "daybreak",
      "the",
      "الفلق",
      "al falaq",
      "falaq",
      "al",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 20,
    },
    "slug": "al-falaq",
    "translations": [
      {
        "language": "en",
        "text": "The Daybreak",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "Al-Falaq",
      },
    ],
    "id": "113",
    "unicode": "&#180;",
  },
  {
    "name": "الناس",
    "number": 114,
    "numberOfAyahs": 6,
    "hasBismillah": true,
    "queryIndexes": [
      "114",
      "the mankind",
      "mankind",
      "the",
      "الناس",
      "an nas",
      "nas",
      "an",
      "makkah",
      "meccan",
    ],
    "revelation": {
      "place": "meccan",
      "order": 21,
    },
    "slug": "an-nas",
    "translations": [
      {
        "language": "en",
        "text": "The Mankind",
      },
    ],
    "transliterations": [
      {
        "language": "en",
        "text": "An-Nas",
      },
    ],
    "id": "114",
    "unicode": "&#181;",
  },
]
