# This is a basic workflow to help you get started with Actions

name: Frontend Web

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./workspace/

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: '14.19.0'

      - name: Install
        run: npm install

      - name: Lint
        run: nx lint frontend-web --max-warnings 0

      - name: Build
        run: nx build frontend-web
